### ISSUE TITLE
Monaco-Linux not a valid font

### ISSUE THREAD

**Issue by MrGrigri** [hbin/top-programming-fonts#5]
## hbin
First of all, Thanks for these awesome fonts. I really Enjoy DejaVu. However, when attempting to install the Monaco-Linux.ttf on my Windows 8.1 Enterprise machine it returns a "Cannot install Monaco-Linux.ttf" error. 

![githubfont](https://cloud.githubusercontent.com/assets/4528551/8786670/b725042c-2eec-11e5-9e58-c6d974de93de.PNG)

### System Specs
Processor: Intell(R) Core(TM) i7-2770 CPU @ 3.40GHz
Memory: 12.0 GB
System Type: 64-bit OS, x64-based

**Comment by hbin** [comment]
Hi, MrGrigri.

Thanks for your feedback. It is obvious that the `Monaco-Linux.ttf` is not valid for Windows. I use these fonts on my laptop with Ubuntu installed.

I found another git repo: https://github.com/todylu/monaco.ttf
You can give it a try. I don't have Windows PC at hand, so I can't help you to test it.

**Comment by MrGrigri** [comment]
Thanks...I don't know much when it comes to fonts. I just thought that all True Type Fonts could be used on systems that support them, which windows does. The DejaVu and Menlo work perfectly on my machine. Thanks again for the response.
